# Generated by Django 5.2.3 on 2025-07-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
        ('accounts', '0004_user_store_custo_first_n_8f83e0_idx_alter_user_table'),
    ]

    operations = [
    ]
